# Generated by Django 5.0 on 2025-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
